import { Prompt } from './types';

type CuratedPrompt = Prompt & {
  mediaType?: 'image' | 'video' | '3d';
  videoUrl?: string;
  durationSeconds?: number;
};

type PromptBlueprint = {
  title: string;
  promptText: string;
  negativePrompt?: string;
  category: Prompt['category'];
  model: string;
  parameters: Record<string, string | number | boolean>;
  seed: string;
  author: string;
};

const VIDEO_URLS = [
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubtitledSintel.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
];

const PROMPT_BLUEPRINTS: PromptBlueprint[] = [
  {
    title: 'Cyberpunk Tokyo Rain',
    promptText: 'Cinematic wide shot of a rainy Tokyo street at night, cyberpunk aesthetic, neon signs reflecting in puddles, futuristic cars, high detail, Unreal Engine render style.',
    negativePrompt: 'blurry, low quality, distorted, simple, daytime',
    category: 'Image',
    model: 'Stable Diffusion XL',
    parameters: { Steps: 40, 'CFG Scale': 7.5, Sampler: 'Euler a', Seed: '3429810' },
    seed: 'cyberpunk-tokyo-rain',
    author: 'NeonExplorer',
  },
  {
    title: 'Ethereal Forest Spirit',
    promptText: 'A majestic spirit made of glowing white light and flowers standing in a mystical ancient forest, rays of light through trees, cinematic lighting, magical atmosphere, hyper-realistic.',
    negativePrompt: 'dark, scary, creepy, buildings, harsh flash',
    category: 'Video',
    model: 'Runway Gen-2',
    parameters: { Motion: 5, 'Fixed Seed': 'True', Upscale: 'On' },
    seed: 'ethereal-forest-spirit',
    author: 'NatureAI',
  },
  {
    title: 'Minimalist Architectural Villa',
    promptText: 'Minimalist white villa nestled in the Swiss Alps, large glass windows, brutalist influence, snow-covered landscape, golden hour lighting, architectural photography style.',
    negativePrompt: 'cluttered, colorful, messy, old, broken',
    category: 'Image',
    model: 'Midjourney v6',
    parameters: { 'Aspect Ratio': '16:9', Stylize: 250, Chaos: 10 },
    seed: 'minimalist-architectural-villa',
    author: 'ArchViz',
  },
  {
    title: 'Futuristic Mecha Core',
    promptText: 'Close up of a highly detailed futuristic mecha engine core, rotating gears, glowing blue plasma, metallic surfaces, industrial design, complex mechanical structure.',
    category: '3D',
    model: 'Spline AI',
    parameters: { 'Polygon Count': 'High', 'Texture Res': '4k', Lighting: 'Studio' },
    seed: 'futuristic-mecha-core',
    author: 'IronSmith',
  },
  {
    title: 'Retro Synthwave Sunset',
    promptText: '80s retro synthwave background, neon sunset, grid landscape, palm tree silhouettes, digital art style, vibrant colors, nostalgic vibes.',
    negativePrompt: 'muted, grayscale, flat, realistic documentary',
    category: 'Image',
    model: 'DALL-E 3',
    parameters: { Style: 'Vivid', Quality: 'HD' },
    seed: 'retro-synthwave-sunset',
    author: 'RetroVibes',
  },
  {
    title: 'Deep Space Nebula',
    promptText: 'A vast colorful nebula in deep space, swirling clouds of gas and stardust, bright distant stars, cosmic horror influence, deep blacks, vibrant violets and oranges.',
    category: 'Video',
    model: 'Pika Labs',
    parameters: { Motion: 8, FPS: 24, Camera: 'Zoom in' },
    seed: 'deep-space-nebula',
    author: 'CosmosAI',
  },
  {
    title: 'Luxury Product Watch Macro',
    promptText: 'Macro product photograph of a luxury mechanical watch on black marble, soft studio highlights, gold accents, visible gears, premium catalog lighting.',
    negativePrompt: 'scratched, cheap plastic, overexposed, watermark',
    category: 'Image',
    model: 'Stable Diffusion XL',
    parameters: { Steps: 36, 'CFG Scale': 8, Sampler: 'DPM++ 2M Karras' },
    seed: 'luxury-watch-macro',
    author: 'ProductFrame',
  },
  {
    title: 'Ocean Drone Surf Chase',
    promptText: 'High-speed drone footage following a surfer carving through turquoise waves, sun flare, cinematic water spray, energetic summer sports film.',
    negativePrompt: 'shaky, dull color, crowded beach, low resolution',
    category: 'Video',
    model: 'Runway Gen-3',
    parameters: { Motion: 7, FPS: 30, Camera: 'Drone chase' },
    seed: 'ocean-drone-surf-chase',
    author: 'AeroScene',
  },
  {
    title: 'Isometric Smart City',
    promptText: 'Detailed isometric smart city district with autonomous cars, rooftop gardens, solar panels, tiny pedestrians, clean futuristic urban planning.',
    category: '3D',
    model: 'Spline AI',
    parameters: { 'Polygon Count': 'Medium', 'Texture Res': '2k', Lighting: 'Ambient occlusion' },
    seed: 'isometric-smart-city',
    author: 'CivicPixel',
  },
  {
    title: 'Editorial Fashion Alley',
    promptText: 'High-fashion editorial portrait in a narrow city alley, dramatic rim light, tailored black outfit, wet pavement, confident pose, magazine cover styling.',
    negativePrompt: 'bad anatomy, cheap fabric, flat lighting, cluttered pose',
    category: 'Image',
    model: 'Midjourney v6',
    parameters: { 'Aspect Ratio': '3:4', Stylize: 500, Chaos: 5 },
    seed: 'editorial-fashion-alley',
    author: 'ModeLab',
  },
  {
    title: 'Ancient Desert Portal',
    promptText: 'Ancient stone portal opening in the desert at sunrise, floating sand particles, carved symbols, cinematic adventure atmosphere, wide angle composition.',
    category: 'Video',
    model: 'Pika Labs',
    parameters: { Motion: 6, FPS: 24, Camera: 'Slow dolly forward' },
    seed: 'ancient-desert-portal',
    author: 'MythMaker',
  },
  {
    title: 'Cozy Reading Nook',
    promptText: 'Warm cozy reading nook beside a rainy window, stacked books, soft blanket, steaming tea, amber lamp light, peaceful lifestyle photography.',
    negativePrompt: 'messy, harsh flash, sterile, cold lighting',
    category: 'Image',
    model: 'DALL-E 3',
    parameters: { Style: 'Natural', Quality: 'HD' },
    seed: 'cozy-reading-nook',
    author: 'SoftFocus',
  },
  {
    title: 'Crystal Cavern Flythrough',
    promptText: 'Cinematic flythrough of a giant crystal cavern, glowing minerals, reflective underground lake, floating dust, fantasy exploration scene.',
    category: 'Video',
    model: 'Runway Gen-2',
    parameters: { Motion: 9, FPS: 24, Camera: 'Flythrough' },
    seed: 'crystal-cavern-flythrough',
    author: 'DepthRender',
  },
  {
    title: 'Robotic Barista Cafe',
    promptText: 'Friendly robotic barista preparing latte art in a modern cafe, polished chrome details, warm interior lighting, near-future lifestyle design.',
    negativePrompt: 'scary robot, messy counter, low detail, distorted hands',
    category: 'Image',
    model: 'Stable Diffusion XL',
    parameters: { Steps: 34, 'CFG Scale': 7, Sampler: 'Euler a' },
    seed: 'robotic-barista-cafe',
    author: 'FutureDaily',
  },
  {
    title: 'Kinetic Logo Reveal',
    promptText: 'Abstract kinetic logo reveal with metallic ribbons, black background, yellow accent glow, smooth studio animation, premium tech brand energy.',
    category: 'Video',
    model: 'Runway Gen-3',
    parameters: { Motion: 8, FPS: 30, Camera: 'Locked studio' },
    seed: 'kinetic-logo-reveal',
    author: 'BrandMotion',
  },
  {
    title: 'Botanical Perfume Bottle',
    promptText: 'Premium perfume bottle surrounded by fresh botanical ingredients, condensation on glass, soft daylight, elegant product photography.',
    negativePrompt: 'plastic, cheap label, noisy, over-saturated',
    category: 'Image',
    model: 'Midjourney v6',
    parameters: { 'Aspect Ratio': '4:5', Stylize: 300, Chaos: 8 },
    seed: 'botanical-perfume-bottle',
    author: 'ScentStudio',
  },
  {
    title: 'Mars Habitat Dawn',
    promptText: 'Realistic Mars research habitat at dawn, astronauts walking between modules, red dust, solar arrays, cinematic science documentary tone.',
    category: 'Image',
    model: 'Stable Diffusion XL',
    parameters: { Steps: 42, 'CFG Scale': 7.5, Sampler: 'DPM++ SDE' },
    seed: 'mars-habitat-dawn',
    author: 'OrbitWorks',
  },
  {
    title: 'Floating Island Kingdom',
    promptText: 'Fantasy kingdom built on floating islands above clouds, waterfalls falling into mist, airships, sunrise light, epic matte painting style.',
    category: 'Video',
    model: 'Pika Labs',
    parameters: { Motion: 5, FPS: 24, Camera: 'Slow orbit' },
    seed: 'floating-island-kingdom',
    author: 'SkyForge',
  },
  {
    title: 'Glassmorphism Dashboard',
    promptText: 'Modern glassmorphism analytics dashboard floating in a dark workspace, luminous charts, clean UI components, product mockup quality.',
    negativePrompt: 'illegible text, messy layout, dated UI, low contrast',
    category: 'Image',
    model: 'DALL-E 3',
    parameters: { Style: 'Vivid', Quality: 'HD' },
    seed: 'glassmorphism-dashboard',
    author: 'InterfaceAI',
  },
  {
    title: 'Wildflower Macro Bee',
    promptText: 'Extreme macro photograph of a bee collecting pollen from a wildflower, shallow depth of field, morning dew, detailed wings, natural color.',
    negativePrompt: 'fake insect, blurry, harsh flash, plastic texture',
    category: 'Image',
    model: 'Stable Diffusion XL',
    parameters: { Steps: 32, 'CFG Scale': 6.5, Sampler: 'DPM++ 2M Karras' },
    seed: 'wildflower-macro-bee',
    author: 'MacroMuse',
  },
  {
    title: 'Neon Motorbike Tunnel',
    promptText: 'Motorbike racing through a futuristic neon tunnel, light streaks, wet chrome reflections, intense motion blur, cinematic action sequence.',
    category: 'Video',
    model: 'Runway Gen-3',
    parameters: { Motion: 10, FPS: 30, Camera: 'Tracking shot' },
    seed: 'neon-motorbike-tunnel',
    author: 'VelocityLab',
  },
  {
    title: 'Handcrafted Ceramic Set',
    promptText: 'Handcrafted ceramic tea set on linen fabric, muted earthy colors, soft natural window light, artisan product photography, tactile clay texture.',
    negativePrompt: 'glossy plastic, factory look, clutter, low detail',
    category: 'Image',
    model: 'Midjourney v6',
    parameters: { 'Aspect Ratio': '1:1', Stylize: 150, Chaos: 4 },
    seed: 'handcrafted-ceramic-set',
    author: 'StudioKiln',
  },
  {
    title: 'Holographic Museum Exhibit',
    promptText: 'Futuristic museum exhibit with holographic ancient artifacts, visitors silhouetted, blue and gold lighting, immersive educational installation.',
    category: '3D',
    model: 'Spline AI',
    parameters: { 'Polygon Count': 'High', 'Texture Res': '4k', Lighting: 'Volumetric' },
    seed: 'holographic-museum-exhibit',
    author: 'MetaGallery',
  },
  {
    title: 'Arctic Research Timelapse',
    promptText: 'Timelapse-style video of an arctic research station under moving aurora lights, snow drift, deep blue night, scientific expedition mood.',
    category: 'Video',
    model: 'Pika Labs',
    parameters: { Motion: 7, FPS: 24, Camera: 'Static timelapse' },
    seed: 'arctic-research-timelapse',
    author: 'PolarFrame',
  },
  {
    title: 'Tropical Resort Pool',
    promptText: 'Luxury tropical resort infinity pool at sunrise, palm shadows, calm turquoise water, elegant architecture, travel magazine photography.',
    negativePrompt: 'crowded, dirty water, cloudy, cheap resort',
    category: 'Image',
    model: 'DALL-E 3',
    parameters: { Style: 'Natural', Quality: 'HD' },
    seed: 'tropical-resort-pool',
    author: 'TravelRender',
  },
  {
    title: 'Animated Food Commercial',
    promptText: 'Slow-motion commercial shot of a gourmet burger being assembled, crisp lettuce, melted cheese, sesame bun, dramatic studio lighting.',
    negativePrompt: 'messy, stale food, low appetite appeal, overcooked',
    category: 'Video',
    model: 'Runway Gen-2',
    parameters: { Motion: 6, FPS: 30, Camera: 'Macro push-in' },
    seed: 'animated-food-commercial',
    author: 'FlavorFrame',
  },
  {
    title: 'Vintage Record Store',
    promptText: 'Nostalgic vintage record store interior, warm afternoon light, rows of vinyl, analog textures, cinematic street photography atmosphere.',
    category: 'Image',
    model: 'Stable Diffusion XL',
    parameters: { Steps: 35, 'CFG Scale': 7, Sampler: 'Euler a' },
    seed: 'vintage-record-store',
    author: 'AnalogDreams',
  },
  {
    title: 'Liquid Metal Sculpture',
    promptText: 'Abstract liquid metal sculpture flowing in a white gallery, mirror reflections, high-end contemporary art render, clean studio lighting.',
    category: '3D',
    model: 'Spline AI',
    parameters: { 'Polygon Count': 'High', 'Texture Res': '4k', Lighting: 'Gallery' },
    seed: 'liquid-metal-sculpture',
    author: 'FormStudio',
  },
  {
    title: 'Rainforest Canopy Glide',
    promptText: 'Smooth aerial glide above dense rainforest canopy, morning mist, sunlight beams, birds crossing frame, nature documentary feeling.',
    category: 'Video',
    model: 'Pika Labs',
    parameters: { Motion: 6, FPS: 24, Camera: 'Aerial glide' },
    seed: 'rainforest-canopy-glide',
    author: 'EcoLens',
  },
  {
    title: 'Luxury Sneaker Hero Shot',
    promptText: 'Premium sneaker hero shot on reflective black acrylic, dynamic yellow rim light, close product detail, modern streetwear campaign.',
    negativePrompt: 'dirty shoe, bad logo, flat lighting, cheap material',
    category: 'Image',
    model: 'Midjourney v6',
    parameters: { 'Aspect Ratio': '16:9', Stylize: 200, Chaos: 6 },
    seed: 'luxury-sneaker-hero-shot',
    author: 'StreetRender',
  },
  {
    title: 'Mythic Dragon Flight',
    promptText: 'Epic dragon flying over jagged mountain peaks, clouds breaking around wings, golden sunrise, fantasy cinematic scale, detailed scales.',
    category: 'Video',
    model: 'Runway Gen-3',
    parameters: { Motion: 9, FPS: 24, Camera: 'Aerial follow' },
    seed: 'mythic-dragon-flight',
    author: 'LegendMotion',
  },
  {
    title: 'Clean SaaS Workspace',
    promptText: 'Modern SaaS workspace with laptop showing analytics UI, clean desk, soft daylight, subtle brand color accents, productive startup mood.',
    negativePrompt: 'messy cables, illegible UI, harsh shadows, clutter',
    category: 'Image',
    model: 'DALL-E 3',
    parameters: { Style: 'Natural', Quality: 'HD' },
    seed: 'clean-saas-workspace',
    author: 'LaunchDesk',
  },
  {
    title: 'Underwater Temple Discovery',
    promptText: 'Divers discovering an ancient underwater temple, shafts of sunlight through blue water, coral growth, cinematic exploration scene.',
    category: 'Video',
    model: 'Pika Labs',
    parameters: { Motion: 5, FPS: 24, Camera: 'Slow reveal' },
    seed: 'underwater-temple-discovery',
    author: 'AquaMyth',
  },
  {
    title: 'AI Chip Closeup',
    promptText: 'Ultra-detailed macro closeup of an AI processor chip, glowing circuit traces, black ceramic package, premium technology product render.',
    negativePrompt: 'dust, damaged pins, fake text, low detail',
    category: 'Image',
    model: 'Stable Diffusion XL',
    parameters: { Steps: 38, 'CFG Scale': 8, Sampler: 'DPM++ 2M Karras' },
    seed: 'ai-chip-closeup',
    author: 'SiliconScene',
  },
  {
    title: 'Paper Cutout Jungle',
    promptText: 'Layered paper cutout jungle scene with colorful birds, handcrafted shadows, playful editorial illustration, crisp paper texture.',
    category: 'Image',
    model: 'Midjourney v6',
    parameters: { 'Aspect Ratio': '4:3', Stylize: 650, Chaos: 12 },
    seed: 'paper-cutout-jungle',
    author: 'CraftPixel',
  },
  {
    title: 'City Hyperlapse Night',
    promptText: 'Hyperlapse through a modern city at night, streaking headlights, glass towers, reflections, energetic urban travel film.',
    category: 'Video',
    model: 'Runway Gen-2',
    parameters: { Motion: 10, FPS: 30, Camera: 'Hyperlapse' },
    seed: 'city-hyperlapse-night',
    author: 'UrbanFlow',
  },
  {
    title: 'Japanese Tea Garden',
    promptText: 'Peaceful Japanese tea garden with stone lantern, koi pond, maple leaves, misty morning, refined natural composition.',
    negativePrompt: 'crowded, modern buildings, harsh sunlight, messy path',
    category: 'Image',
    model: 'DALL-E 3',
    parameters: { Style: 'Natural', Quality: 'HD' },
    seed: 'japanese-tea-garden',
    author: 'ZenFrame',
  },
  {
    title: 'Solarpunk Market Street',
    promptText: 'Bright solarpunk market street with hanging gardens, colorful awnings, clean transit, community atmosphere, optimistic future city.',
    category: 'Image',
    model: 'Stable Diffusion XL',
    parameters: { Steps: 40, 'CFG Scale': 7.5, Sampler: 'Euler a' },
    seed: 'solarpunk-market-street',
    author: 'GreenCircuit',
  },
  {
    title: 'Abstract Data Tunnel',
    promptText: 'Abstract tunnel of glowing data streams, particles flowing toward camera, black background, cyan and yellow highlights, AI network visualization.',
    category: 'Video',
    model: 'Runway Gen-3',
    parameters: { Motion: 8, FPS: 30, Camera: 'Forward tunnel' },
    seed: 'abstract-data-tunnel',
    author: 'DataPulse',
  },
  {
    title: 'Nordic Cabin Interior',
    promptText: 'Minimal Nordic cabin interior with fireplace, pale wood, wool textiles, large snowy window view, calm lifestyle architecture photography.',
    negativePrompt: 'cluttered, dark, dirty, overdecorated',
    category: 'Image',
    model: 'Midjourney v6',
    parameters: { 'Aspect Ratio': '16:9', Stylize: 100, Chaos: 3 },
    seed: 'nordic-cabin-interior',
    author: 'HyggeLens',
  },
  {
    title: 'Galaxy Marble Sculpture',
    promptText: 'Surreal marble sculpture containing a tiny galaxy inside translucent stone, museum pedestal, dramatic spotlight, impossible materials.',
    category: '3D',
    model: 'Spline AI',
    parameters: { 'Polygon Count': 'High', 'Texture Res': '4k', Lighting: 'Spotlight' },
    seed: 'galaxy-marble-sculpture',
    author: 'SurrealForms',
  },
  {
    title: 'Desert Rally Dust Trail',
    promptText: 'Cinematic desert rally car speeding across dunes, massive dust trail, sunset backlight, action sports photography energy.',
    category: 'Video',
    model: 'Pika Labs',
    parameters: { Motion: 9, FPS: 30, Camera: 'Side tracking' },
    seed: 'desert-rally-dust-trail',
    author: 'DustRunner',
  },
  {
    title: 'Premium App Icon Set',
    promptText: 'Set of premium app icons on dark background, glassy materials, consistent grid, rounded squares, luminous yellow accent, product design showcase.',
    negativePrompt: 'messy spacing, inconsistent style, unreadable symbols',
    category: 'Image',
    model: 'DALL-E 3',
    parameters: { Style: 'Vivid', Quality: 'HD' },
    seed: 'premium-app-icon-set',
    author: 'IconForge',
  },
  {
    title: 'Neoclassical Robot Portrait',
    promptText: 'Neoclassical oil painting portrait of a refined humanoid robot, velvet background, golden frame lighting, museum-grade brushwork.',
    negativePrompt: 'cartoonish, flat, noisy, distorted face',
    category: 'Image',
    model: 'Midjourney v6',
    parameters: { 'Aspect Ratio': '3:4', Stylize: 700, Chaos: 7 },
    seed: 'neoclassical-robot-portrait',
    author: 'CanvasFuture',
  },
  {
    title: 'Mountain Bike Forest Run',
    promptText: 'Dynamic POV mountain bike ride through dense forest trail, sun flicker through trees, dirt particles, adrenaline sports footage.',
    category: 'Video',
    model: 'Runway Gen-2',
    parameters: { Motion: 10, FPS: 30, Camera: 'POV' },
    seed: 'mountain-bike-forest-run',
    author: 'TrailMotion',
  },
  {
    title: 'Luxury Hotel Lobby',
    promptText: 'Grand luxury hotel lobby with sculptural chandelier, marble floor, velvet seating, warm ambient lighting, hospitality architecture photography.',
    negativePrompt: 'empty cheap room, low ceiling, clutter, bad lighting',
    category: 'Image',
    model: 'Stable Diffusion XL',
    parameters: { Steps: 37, 'CFG Scale': 7.2, Sampler: 'DPM++ SDE' },
    seed: 'luxury-hotel-lobby',
    author: 'LobbyLight',
  },
  {
    title: 'Animated Neon Typography',
    promptText: 'Animated neon typography spelling FUTURE MODE, letters flicker on black brick wall, yellow and magenta glow, music video intro style.',
    negativePrompt: 'misspelled text, unreadable letters, dull glow',
    category: 'Video',
    model: 'Runway Gen-3',
    parameters: { Motion: 6, FPS: 24, Camera: 'Locked frontal' },
    seed: 'animated-neon-typography',
    author: 'TypeMotion',
  },
  {
    title: 'Futuristic Medical Lab',
    promptText: 'Clean futuristic medical research lab, transparent displays, robotic microscope arms, cool white lighting, realistic healthcare innovation scene.',
    negativePrompt: 'dirty, scary, gore, cluttered cables',
    category: 'Image',
    model: 'DALL-E 3',
    parameters: { Style: 'Natural', Quality: 'HD' },
    seed: 'futuristic-medical-lab',
    author: 'MedFuture',
  },
  {
    title: 'Origami Spacecraft Fleet',
    promptText: 'Fleet of origami spacecraft flying through a starfield, folded paper texture, elegant sci-fi whimsy, cinematic lighting.',
    category: '3D',
    model: 'Spline AI',
    parameters: { 'Polygon Count': 'Medium', 'Texture Res': '2k', Lighting: 'Cinematic' },
    seed: 'origami-spacecraft-fleet',
    author: 'PaperOrbit',
  },
  {
    title: 'Watercolor Coastal Village',
    promptText: 'Soft watercolor painting of a coastal village on cliffs, fishing boats, pastel sky, gentle sea, handmade paper texture.',
    negativePrompt: 'photorealistic, harsh black outlines, muddy colors',
    category: 'Image',
    model: 'Midjourney v6',
    parameters: { 'Aspect Ratio': '4:3', Stylize: 800, Chaos: 15 },
    seed: 'watercolor-coastal-village',
    author: 'WashStudio',
  },
  {
    title: 'Bioluminescent Ocean Dive',
    promptText: 'Night dive through bioluminescent ocean life, glowing plankton trails, diver silhouette, dreamlike underwater motion.',
    category: 'Video',
    model: 'Pika Labs',
    parameters: { Motion: 6, FPS: 24, Camera: 'Slow drift' },
    seed: 'bioluminescent-ocean-dive',
    author: 'BlueGlow',
  },
];

const variationNotes = [
  'Add premium cinematic contrast and crisp foreground detail.',
  'Use a slightly wider composition with stronger environmental storytelling.',
  'Emphasize dramatic lighting, tactile materials, and layered depth.',
  'Make the color palette more refined while preserving the original concept.',
  'Push the composition toward a high-end campaign or hero-shot finish.',
  'Add subtle atmospheric particles and richer background detail.',
  'Use a cleaner editorial layout with sharper subject separation.',
  'Increase realism, texture fidelity, and production-design polish.',
  'Make the mood more immersive with stronger camera direction.',
  'Add a futuristic premium finish without making the scene cluttered.',
];

const dateFor = (index: number) => {
  const day = (index % 110) + 1;
  const date = new Date(Date.UTC(2026, 0, day));
  return date.toISOString().slice(0, 10);
};

const imageUrlFor = (seed: string, index: number) =>
  `https://picsum.photos/seed/${encodeURIComponent(`${seed}-${index + 1}`)}/1200/800`;

export const CURATED_PROMPTS: CuratedPrompt[] = Array.from({ length: 1000 }, (_, index) => {
  const base = PROMPT_BLUEPRINTS[index % PROMPT_BLUEPRINTS.length];
  const batch = Math.floor(index / PROMPT_BLUEPRINTS.length) + 1;
  const variation = variationNotes[index % variationNotes.length];
  const isVideo = base.category === 'Video';
  const is3d = base.category === '3D';

  return {
    id: String(index + 1),
    title: batch === 1 ? base.title : `${base.title} ${String(batch).padStart(2, '0')}`,
    promptText: `${base.promptText} ${variation}`,
    negativePrompt: base.negativePrompt,
    category: base.category,
    model: base.model,
    parameters: {
      ...base.parameters,
      Variant: batch,
      'Preview Quality': index % 3 === 0 ? 'High' : 'Standard',
    },
    imageUrl: imageUrlFor(base.seed, index),
    mediaType: isVideo ? 'video' : is3d ? '3d' : 'image',
    videoUrl: isVideo ? VIDEO_URLS[index % VIDEO_URLS.length] : undefined,
    durationSeconds: isVideo ? [5, 8, 10, 12, 15][index % 5] : undefined,
    author: base.author,
    createdAt: dateFor(index),
  };
});
